### ISSUE TITLE
Version control issue

### ISSUE THREAD

**Issue by royb3** [AzerPUG/Core#16]
These addons have issues with Version control

- [ ] Interrupt Helper
- [ ] Multiple Reputation Tracker
- [ ] Mana Management

**Comment by Arco-Dielhof** [comment]
What exactly is wrong with the Version Control in them?

**Comment by royb3** [comment]
They send their versions separately instead of with Core, when core is
enabled.

Op do 29 jul. 2021 om 09:58 schreef Arco-Dielhof ***@***.***>:

**Comment by royb3** [comment]
Gonna rewrite version control soon anyway.
